name: lifeiscontent
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25221
title: Thoughts and Tutorials from Aaron Reisman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27661375-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#9ea5af'
    - '#0f1128'
    - '#636e8c'
    - '#394155'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
