name: lifeiscontent
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25221
title: Thoughts and Tutorials from Aaron Reisman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27661375-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f7f7f'
    - '#79aae3'
    - '#3d3c44'
    - '#215294'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
