name: lifeiscontent
favicon: null
layout_spectrum: 0.5570518504828215
typography_spectrum: 0.7550253444351256
title: Thoughts and Tutorials from Aaron Reisman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27661375-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.638366136001423
  lightness: 0.8063908261246979
  saturation: 0.18212482100352645
  rhythmicContrast: 0.987527743447572
purpose: []
